APP_ID = "YOUR_FYERS_APP_ID"
SECRET_KEY = "YOUR_SECRET_KEY"
REDIRECT_URI = "YOUR_REDIRECT_URI"

CAPITAL = 20000
TRADE_VALUE = 8000

MAX_TRADES = 2
MAX_LOSS = -300

AUTO_EXIT_TIME = "15:15"
AUTO_PAUSE_ENABLED = False   # keep FALSE initially
KILL_SWITCH = False
